name: Push to Octopus Server

on:
  release:
    types: [created]

  workflow_dispatch:
    inputs:
      release-tag:
        description: "The tag of the release being replicated in Octopus Deploy"
        required: true

jobs:
  build:
    name: "Push Package and Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'

      - name: Build with gradle
        run: ./gradlew build test

      - name: Create Plugin Zip Deployment
        id: create-package
        run: |
          ./gradlew distZip
          PACKAGE_NAME=`./gradlew -q packageName`
          echo "::set-output name=package-created::$PACKAGE_NAME"
          VERSION=`./gradlew properties | grep ^version | awk '{print $2;}'`
          echo "::set-output name=version::$VERSION"
      - name: Output test stuff
        run: |
          echo ${{ steps.create-package.outputs.package-created }}
          echo ${{ steps.create-package.outputs.version }}
